import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { shareReplay, map, mergeMap, switchMap } from 'rxjs/operators';
import { interval } from 'rxjs';

@Injectable({
  providedIn: 'root',
  deps: [HttpClient]
})
export class QuoteService {
  quotes$ = this.http
    .get<Quote[]>('https://talaikis.com/api/quotes/')
    .pipe(shareReplay(1));

  quoteLength$ = this.quotes$.pipe(
    map(list => list.length),
    shareReplay(1)
  );

  quoteObs = (idx: number) => this.quotes$.pipe(map(list => list[idx]));

  RandomQuoteOnIntervalObs = (time: number) =>
    interval(time).pipe(
      switchMap(() => this.quoteLength$),
      map(length => Math.floor(Math.random() * length)),
      mergeMap(this.quoteObs)
    );

  constructor(private http: HttpClient) {}
}

// Generated by https://quicktype.io

export interface Quote {
  quote: string;
  author: string;
  cat: string;
}
